import {
  LuArrowRight,
  LuArrowUp,
  LuArrowUpRight,
  LuAward,
  LuBot,
  LuBrain,
  LuCheck,
  LuCodeXml,
  LuCopy,
  LuCpu,
  LuFileText,
  LuGitBranch,
  LuGraduationCap,
  LuGuitar,
  LuLayers,
  LuMail,
  LuMapPin,
  LuMapPinned,
  LuMenu,
  LuNetwork,
  LuPawPrint,
  LuPlane,
  LuQrCode,
  LuScanEye,
  LuShare2,
  LuSmartphone,
  LuSparkles,
  LuUserPlus,
  LuUsers,
  LuWifiOff,
  LuX,
} from "react-icons/lu";
import { FaGooglePlay, FaLinkedinIn, FaMicrosoft } from "react-icons/fa";
import { GiSoccerBall } from "react-icons/gi";
import { SiGithub } from "react-icons/si";

const icons = {
  arrow: LuArrowRight,
  arrowUp: LuArrowUp,
  external: LuArrowUpRight,
  award: LuAward,
  bot: LuBot,
  brain: LuBrain,
  check: LuCheck,
  code: LuCodeXml,
  copy: LuCopy,
  cpu: LuCpu,
  file: LuFileText,
  football: GiSoccerBall,
  github: SiGithub,
  guitar: LuGuitar,
  layers: LuLayers,
  linkedin: FaLinkedinIn,
  mail: LuMail,
  map: LuMapPinned,
  menu: LuMenu,
  microsoft: FaMicrosoft,
  network: LuNetwork,
  offline: LuWifiOff,
  paw: LuPawPrint,
  pin: LuMapPin,
  plane: LuPlane,
  play: FaGooglePlay,
  qr: LuQrCode,
  share: LuShare2,
  phone: LuSmartphone,
  sparkles: LuSparkles,
  teach: LuGraduationCap,
  tree: LuGitBranch,
  userPlus: LuUserPlus,
  users: LuUsers,
  vision: LuScanEye,
  close: LuX,
};

export default function Icon({ name, className = "h-5 w-5" }) {
  const Component = icons[name] || LuSparkles;
  return <Component className={className} aria-hidden="true" focusable="false" />;
}
